#Makefile for compilations
all:
	$(MAKE) -C ../ all

test:
	$(MAKE) -C ../ test

decode:
	$(MAKE) -C ../ decode

simple:
	$(MAKE) -C ../ simple

dataflow:
	$(MAKE) -C ../ dataflow

clean:
	$(MAKE) -C ../ clean
